create table payment_order (
    payment_id varchar(40) primary key,
    order_id varchar(40) not null,
    merchant_id varchar(32) not null,
    amount numeric(20, 4) not null,
    currency char(3) not null,
    status varchar(24) not null,
    selected_channel varchar(32),
    route_version varchar(32),
    idempotency_key varchar(64) not null,
    version bigint not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_payment_merchant_idempotency unique (merchant_id, idempotency_key)
);

create index idx_payment_status_updated
    on payment_order (status, updated_at);

create table payment_attempt (
    attempt_id varchar(40) primary key,
    payment_id varchar(40) not null,
    channel varchar(32) not null,
    request_id varchar(64) not null,
    result varchar(24) not null,
    channel_code varchar(32),
    started_at timestamp with time zone not null,
    finished_at timestamp with time zone,
    constraint fk_payment_attempt_order
        foreign key (payment_id) references payment_order (payment_id)
);

create index idx_payment_attempt_payment
    on payment_attempt (payment_id, started_at);

create table payment_event (
    sequence_id bigint generated by default as identity primary key,
    payment_id varchar(40) not null,
    event_type varchar(64) not null,
    event_time timestamp with time zone not null,
    source varchar(32) not null,
    trace_id varchar(32),
    details jsonb not null,
    constraint fk_payment_event_order
        foreign key (payment_id) references payment_order (payment_id)
);

create index idx_payment_event_timeline
    on payment_event (payment_id, sequence_id);

create table outbox_event (
    event_id uuid primary key,
    aggregate_id varchar(40) not null,
    event_type varchar(64) not null,
    payload jsonb not null,
    created_at timestamp with time zone not null,
    published_at timestamp with time zone
);

create index idx_outbox_unpublished
    on outbox_event (created_at)
    where published_at is null;
