create table incident (
    incident_id varchar(40) primary key,
    aggregate_key varchar(200) not null,
    status varchar(32) not null,
    detected_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null
);

create index idx_incident_open_aggregation
    on incident (aggregate_key, status, detected_at);

create table incident_alert (
    incident_id varchar(40) not null,
    alert_id varchar(120) not null,
    source varchar(32) not null,
    service varchar(80) not null,
    signal_name varchar(120) not null,
    severity varchar(24) not null,
    starts_at timestamp with time zone not null,
    dimensions jsonb not null,
    observed_value numeric(20, 4),
    threshold numeric(20, 4),
    constraint pk_incident_alert primary key (incident_id, alert_id),
    constraint uk_incident_alert_id unique (alert_id),
    constraint fk_incident_alert_incident
        foreign key (incident_id) references incident (incident_id)
);

create table incident_timeline (
    sequence_id bigint generated by default as identity primary key,
    incident_id varchar(40) not null,
    event_type varchar(64) not null,
    event_time timestamp with time zone not null,
    details jsonb not null,
    constraint fk_incident_timeline_incident
        foreign key (incident_id) references incident (incident_id)
);

create index idx_incident_timeline_order
    on incident_timeline (incident_id, sequence_id);
