FROM eclipse-temurin:21-jre-alpine

RUN addgroup -g 10001 -S paysre && \
    adduser -u 10001 -S paysre -G paysre
WORKDIR /app
COPY --chown=paysre:paysre app.jar /app/app.jar

USER paysre
EXPOSE 8080 8081 8082
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/app.jar"]
