import { useEffect, useState } from 'react';

/**
 * Renders the contents of docs/superpowers/reports/benchmark-baseline.md
 * via the Vite dev server's static asset pipeline. The Markdown is
 * not parsed client-side; the page shows it as a code block so the
 * numbers and policy summary stay exactly as the test wrote them.
 */
export function BenchmarkPage() {
  const [markdown, setMarkdown] = useState<string | null>(null);

  useEffect(() => {
    fetch('/benchmark-baseline.md')
      .then((res) => (res.ok ? res.text() : Promise.reject(res.statusText)))
      .then(setMarkdown)
      .catch(() => setMarkdown('(benchmark-baseline.md not served)'));
  }, []);

  return (
    <div className="card">
      <h2>PaySRE Benchmark — Stub baseline</h2>
      <p>
        Regenerated by <code>BenchmarkReportGeneratorTest</code> whenever the
        fault catalog or the root cause policy registry changes. Multi-model
        matrix is added in R8 once R3b supplies <code>MINIMAX_API_KEY</code>.
      </p>
      <pre
        style={{
          background: '#0f172a',
          color: '#e0f2fe',
          padding: '0.8rem',
          borderRadius: 4,
          overflowX: 'auto',
          fontSize: '0.82rem',
        }}
      >
        {markdown ?? 'loading…'}
      </pre>
    </div>
  );
}