spring:
  application:
    name: sre-control-plane
  datasource:
    url: ${CONTROL_DB_URL:jdbc:postgresql://localhost:5432/paysre_control}
    username: ${CONTROL_DB_USERNAME:paysre}
    password: ${CONTROL_DB_PASSWORD:paysre}
  flyway:
    enabled: true

paysre:
  payment:
    base-url: ${PAYMENT_SERVICE_BASE_URL:http://localhost:8080}
  channel:
    base-url: ${CHANNEL_SIMULATOR_BASE_URL:http://localhost:8081}

server:
  port: ${CONTROL_PLANE_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
