package io.paysre.payment.application;

import static org.assertj.core.api.Assertions.assertThat;

import io.paysre.contracts.Money;
import io.paysre.payment.adapter.persistence.JdbcPaymentRepository;
import io.paysre.payment.domain.PaymentOrder;
import io.paysre.payment.domain.PaymentStatus;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.Currency;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class JdbcPaymentRepositoryTest {

    private JdbcPaymentRepository repository;

    @BeforeEach
    void setUp() {
        var dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:payments;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE");
        var jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("drop table if exists payment_event");
        jdbc.execute("drop table if exists payment_order");
        jdbc.execute("""
                create table payment_order (
                    payment_id varchar(40) primary key,
                    order_id varchar(40) not null,
                    merchant_id varchar(32) not null,
                    amount numeric(20, 4) not null,
                    currency char(3) not null,
                    status varchar(24) not null,
                    selected_channel varchar(32),
                    route_version varchar(32),
                    idempotency_key varchar(64) not null,
                    version bigint not null,
                    created_at timestamp with time zone not null,
                    updated_at timestamp with time zone not null,
                    unique (merchant_id, idempotency_key)
                )
                """);
        jdbc.execute("""
                create table payment_event (
                    sequence_id bigint generated by default as identity primary key,
                    payment_id varchar(40) not null,
                    event_type varchar(64) not null,
                    event_time timestamp with time zone not null,
                    source varchar(32) not null,
                    trace_id varchar(32),
                    details jsonb not null
                )
                """);
        repository = new JdbcPaymentRepository(jdbc);
    }

    @Test
    void persistsAndRestoresTheAggregateAndOrderedTimeline() {
        var payment = processingPayment("P10001");
        repository.save(payment, "IDEMPOTENCY-1");
        payment.markUnknown("CHANNEL_TIMEOUT", Instant.EPOCH.plusSeconds(1));
        repository.save(payment, "IDEMPOTENCY-1");

        var restored = repository.findByPaymentId("P10001").orElseThrow();

        assertThat(restored.status()).isEqualTo(PaymentStatus.UNKNOWN);
        assertThat(restored.version()).isEqualTo(1L);
        assertThat(restored.events()).hasSize(3);
        assertThat(restored.events()).extracting(event -> event.reasonCode())
                .containsExactly("CREATED", "CHANNEL_SELECTED", "CHANNEL_TIMEOUT");
    }

    @Test
    void duplicateMerchantIdempotencyKeyReturnsTheExistingPayment() {
        var first = processingPayment("P10001");
        repository.save(first, "IDEMPOTENCY-1");

        var duplicate = repository.save(processingPayment("P10002"), "IDEMPOTENCY-1");

        assertThat(duplicate.paymentId()).isEqualTo("P10001");
    }

    @Test
    void queriesOnlyUnknownPaymentsInTheRequestedTimeWindow() {
        var unknown = processingPayment("P10001");
        repository.save(unknown, "IDEMPOTENCY-1");
        unknown.markUnknown("CHANNEL_TIMEOUT", Instant.EPOCH.plusSeconds(1));
        repository.save(unknown, "IDEMPOTENCY-1");

        var result = repository.findUnknown(
                Instant.EPOCH, Instant.EPOCH.plusSeconds(60), 50);

        assertThat(result).singleElement()
                .satisfies(payment -> {
                    assertThat(payment.paymentId()).isEqualTo("P10001");
                    assertThat(payment.status()).isEqualTo(PaymentStatus.UNKNOWN);
                });
    }

    private PaymentOrder processingPayment(String paymentId) {
        var payment = PaymentOrder.create(
                paymentId,
                "O10001",
                "M001",
                new Money(new BigDecimal("10.00"), Currency.getInstance("CNY")),
                Instant.EPOCH);
        payment.start("CHANNEL_A", "route-v1", Instant.EPOCH);
        return payment;
    }
}
