spring:
  application:
    name: payment-service
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/paysre}
    username: ${PAYMENT_DB_USERNAME:paysre}
    password: ${PAYMENT_DB_PASSWORD:paysre}
  flyway:
    enabled: true

server:
  port: ${PAYMENT_SERVICE_PORT:8080}

paysre:
  channel:
    base-url: ${CHANNEL_BASE_URL:http://localhost:8081}
