package io.paysre.control.investigation;

public enum RootCauseCode {
    CHANNEL_TIMEOUT_RESPONSE_LOST,
    CHANNEL_DECLINE_SPIKE,
    CHANNEL_CODE_MAPPING_ERROR,
    CHANNEL_CALLBACK_LOST,
    ROUTING_MISCONFIGURED
}