package io.paysre.control.incident;

import static org.assertj.core.api.Assertions.assertThat;

import io.paysre.control.adapter.persistence.JdbcIncidentRepository;
import io.paysre.control.alerting.AlertSignal;
import io.paysre.control.alerting.Severity;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class JdbcIncidentRepositoryTest {

    private JdbcTemplate jdbc;
    private JdbcIncidentRepository repository;

    @BeforeEach
    void setUp() {
        var dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:incidents;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("drop table if exists incident_timeline");
        jdbc.execute("drop table if exists incident_alert");
        jdbc.execute("drop table if exists incident");
        jdbc.execute("""
                create table incident (
                    incident_id varchar(40) primary key,
                    aggregate_key varchar(200) not null,
                    status varchar(32) not null,
                    detected_at timestamp with time zone not null,
                    updated_at timestamp with time zone not null,
                    version bigint not null
                )
                """);
        jdbc.execute("""
                create table incident_alert (
                    incident_id varchar(40) not null,
                    alert_id varchar(120) not null unique,
                    source varchar(32) not null,
                    service varchar(80) not null,
                    signal_name varchar(120) not null,
                    severity varchar(24) not null,
                    starts_at timestamp with time zone not null,
                    dimensions jsonb not null,
                    observed_value numeric(20, 4),
                    threshold numeric(20, 4),
                    primary key (incident_id, alert_id)
                )
                """);
        jdbc.execute("""
                create table incident_timeline (
                    sequence_id bigint generated by default as identity primary key,
                    incident_id varchar(40) not null,
                    event_type varchar(64) not null,
                    event_time timestamp with time zone not null,
                    details jsonb not null
                )
                """);
        repository = new JdbcIncidentRepository(jdbc);
    }

    @Test
    void persistsAlertAssociationsAndTimelineAndRestoresTheIncident() {
        var service = new IncidentApplicationService(repository, () -> "INC-01");

        service.ingest(alert("A-1", Instant.EPOCH));
        service.ingest(alert("A-2", Instant.EPOCH.plusSeconds(60)));
        var restored = repository.findById("INC-01").orElseThrow();

        assertThat(restored.alertIds()).containsExactly("A-1", "A-2");
        assertThat(restored.version()).isEqualTo(1L);
        assertThat(jdbc.queryForObject(
                        "select count(*) from incident_timeline where incident_id = 'INC-01'",
                        Integer.class))
                .isEqualTo(3);
    }

    private AlertSignal alert(String alertId, Instant startsAt) {
        return new AlertSignal(
                alertId,
                "ALERTMANAGER",
                "payment-service",
                "payment_unknown_current",
                Severity.HIGH,
                startsAt,
                Map.of("channel", "CHANNEL_A"),
                new BigDecimal("5"),
                new BigDecimal("1"));
    }
}
